name: CI

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - '**'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        command: [check, test]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs

      - name: Auth for pypi
        run: |
          poetry config http-basic.omnia-prevent ${{ secrets.PIP_USERNAME }} ${{ secret.PIP_PASSWORD }}

      - name: Upgrade pip
        run: |
          poetry run pip install --upgrade pip

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: ~/.virtualenvs
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install

      - name: Running the Check
        run: poetry run inv ${{ matrix.command }}
