name: CI

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - '**'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        command: [check, test]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.1.13
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs

      - name: Auth for pypi
        run: |
          poetry config http-basic.gordo ${{ secrets.PIP_USERNAME }} ${{ secrets.PIP_PASSWORD }}

      - name: Upgrade pip
        run: |
          poetry run pip install --upgrade pip

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: ~/.virtualenvs
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install

      - name: Unset poetry config
        run: poetry config --unset http-basic.gordo

      - name: Running the Check
        run: poetry run inv ${{ matrix.command }}
