name: PiPY Publish

on:
  push:
    tags:
      - 'v*'
      - '!v*dev*'
jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Set tag version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:11}

      - name : Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: 'x64'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: ~/.virtualenvs
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Set tag version
#        if: ${{ !startsWith(github.ref , 'refs/pull/') && !startsWith(github.ref , 'refs/tags/') }}
        run: poetry version ${{ steps.vars.outputs.tag }}
#        run: poetry version ${{ steps.versioning.outputs.tag }}

      - name: Build
#        if: ${{ !startsWith(github.ref , 'refs/pull/') && !startsWith(github.ref , 'refs/tags/') }}
        run: poetry build

      - name: Pypi Publish
#        if: ${{ !startsWith(github.ref , 'refs/pull/') && !startsWith(github.ref , 'refs/tags/') }}
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
