name: PiPY Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Check version
        run: bash ci/check_version.sh ${GITHUB_REF#refs/tags/}

      - name : Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        with:
          path: ~/.virtualenvs
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install twine
        run: |
          pip install twine
      
      - name: Build
        run: |
          poetry build -f wheel

      - name: Pypi Publish
        run: |
          twine upload --skip-existing --repository-url "${{ secrets.PYPI_REPOSITORY }}" -u "${{ secrets.PYPI_USERNAME }}" -p "${{ secrets.PYPI_PASSWORD }}" dist/*
