name: Versioning

on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  versioning:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch origin "+refs/tags/*:refs/tags/*"

      - name: Semantic versioning
        id: versioning
        uses: equinor/semantic-version@v4.2.0
        with:
          branch: master
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          main_format: "${major}.${minor}.${patch}"
          increment_format: "${increment}"
          increment_delimiter: "dev"

      - name: Create Release
        if: ${{ !startsWith(github.ref , 'refs/pull/') && !startsWith(github.ref , 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioning.outputs.tag }}
          release_name: ${{ steps.versioning.outputs.tag }}
          prerelease: true
